# Oct 30 2025

# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__      # This will show current version of your numpy

'2.1.3'

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

# Now Convert List To Array

In [6]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)         # my list type changed to array

numpy.ndarray

# arange

In [8]:
np.arange(10)    # (int) index starts with 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5.0)   # float

array([0., 1., 2., 3., 4.])

In [10]:
np.arange(10,20)    # 10 is start index and 20 is stop index

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(20,10)    # first argument should be less than second argument so we got empty list

array([], dtype=int64)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [14]:
ar=np.arange(-30,20)    # Multi dimentional array
ar                   

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [15]:
np.arange()    # arange requires a stop to be specified

TypeError: arange() requires stop to be specified.

In [16]:
np.arange(10,30,5)       # 10 is start, 30 is stop and 5 is step

array([10, 15, 20, 25])

In [17]:
np.arange(10,30,5,8)     # error = only three arguments allowed start,stop,step

TypeError: Cannot interpret '8' as a data type

# Zeros

In [18]:
np.zeros(5)     # Paramter tuning, by default this is float
                # to convert into int use hyper parameter tuning

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5,dtype=int)      # Hyper parameter tuning

array([0, 0, 0, 0, 0])

In [20]:
np.zeros((2,2),dtype=int)   # Two dimensional array

array([[0, 0],
       [0, 0]])

In [21]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [22]:
np.zeros((2,10))         # 2*10 matrix (or) 2/10 matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((10,10),dtype=int)      # 10*10 matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Ones

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
np.two((2,3))      # Error Because 2 is not defined in numpy only zeros and ones

AttributeError: module 'numpy' has no attribute 'two'

In [30]:
np.random.rand(3)    # np is a Package, random = module, rand is a function() which will generate three random numbers
                     # everytime you execute this code every time it will give new random numbers

array([0.25942392, 0.33683904, 0.76898629])

In [31]:
np.random.rand(2,2)     # Used for OTP's

array([[0.49327918, 0.43664111],
       [0.8487197 , 0.2660206 ]])

In [32]:
np.random.randint(2,20,4)    # Generate four random integers between 2 and 20

array([10, 19, 15,  8], dtype=int32)

In [33]:
np.random.randint(30,20,10)   # Error Because first argument should be less than second argument

ValueError: low >= high

In [34]:
np.random.randint(-30,20,10)

array([-25,   0, -15,  18, -26, -19,   8, -19, -14,  10], dtype=int32)

In [35]:
np.random.randint(10,40,(10,10))    # 10*10 Matrix and 10 Random Values Between 10 and 40

array([[20, 27, 39, 33, 20, 30, 12, 10, 29, 33],
       [39, 36, 14, 29, 24, 38, 16, 22, 10, 17],
       [39, 38, 18, 10, 20, 21, 29, 23, 25, 15],
       [25, 16, 32, 37, 12, 38, 35, 32, 39, 14],
       [29, 15, 21, 29, 36, 32, 33, 11, 39, 15],
       [12, 31, 38, 35, 22, 34, 34, 38, 15, 22],
       [13, 18, 29, 39, 34, 33, 29, 20, 23, 18],
       [17, 14, 35, 28, 33, 37, 26, 28, 27, 33],
       [30, 17, 12, 19, 14, 31, 12, 24, 13, 15],
       [21, 16, 16, 34, 32, 19, 17, 12, 32, 11]], dtype=int32)

# Reshape

In [36]:
np.arange(1,13)    # 12 Values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
np.arange(1,13).reshape(3,4)   # we are reshaping those 12 values in 3*4 matrix
                               # (2,6) (3,4) (4,3) (6,2) anything you can use but final output should be 12
                               # i only have 12 values if i give (3,5) =15 values so error
                               # Matrix should match the no of values or elements

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Slicing in Matrix

In [38]:
b=np.random.randint(10,20,(5,4))
b 

array([[14, 10, 14, 15],
       [15, 12, 18, 10],
       [14, 11, 10, 12],
       [19, 17, 18, 19],
       [19, 15, 19, 19]], dtype=int32)

In [ ]:
# The Numbers i have written around the matrix is forward and backward indexes 
# so based on our input index the array will give output index 

      # 0   1   2    3
   # 1 [14, 10, 14, 15], -5
   # 2 [15, 12, 18, 10], -4
   # 3 [14, 11, 10, 12], -3
   # 4 [19, 17, 18, 19], -2
   # 5 [19, 15, 19, 19]] -1
     # -4   -3  -2  -1 

In [39]:
b[0]

array([14, 10, 14, 15], dtype=int32)

In [40]:
b[3]

array([19, 17, 18, 19], dtype=int32)

In [41]:
b[-4]

array([15, 12, 18, 10], dtype=int32)