# Oct 31 2025

In [1]:
import numpy as np       # importing numpy library to python

In [2]:
# Remeber In Python Forward Index Starts With Zero = first element, so First row or First Column means Zero row or column 
# Backward Index Starts With -1. so -1 means first column or first row from reverse

In [3]:
b=np.random.randint(10,20,(5,4))
b                                  # this will create random values between 10 and 20 in 5*4 matrix form

array([[14, 19, 19, 12],
       [16, 18, 17, 18],
       [12, 18, 16, 18],
       [11, 18, 16, 17],
       [18, 12, 14, 16]], dtype=int32)

In [4]:
# These are the indexes 
    #     0   1   2    3
   # 0  [14, 19, 19, 12],   -5 
   # 1  [16, 18, 17, 18],   -4
   # 2  [12, 18, 16, 18],   -3
   # 3  [11, 18, 16, 17],   -2
   # 4  [18, 12, 14, 16],   -1
   #     -4  -3  -2  -1

In [6]:
b = b.astype(int)       # used for converting our variable into integer form or simply you can use print it will also print integer value

In [7]:
print(b[0,3])  # 0,3 means first row third index element
               # your array is a NumPy array with dtype=int32, so when you access an element like b[0,3], 
               # it returns a NumPy scalar (np.int32), not a normal Python int, so we are using print to get the integer output

12


In [8]:
print(int(b[0,3]))    # : = it will parse rows or columns
                      # , = it gives output of specific values

12


In [9]:
print(b[1,2])  # 2nd row 2nd index element   
               # based on your given input it will take that specifi value from above matrix and gives output

17


In [10]:
print(b[1,-1])  # 2nd row first element from reverse 

18


In [11]:
print(b[0,-2])   # first row, second element from reverse

19


In [12]:
print(b[-3,3])   # third row in reverse and 3rd index element 

18


In [13]:
print(b[-5])    # first full row 

[14 19 19 12]


# Numpy Operations

In [14]:
a=np.random.randint(10,20,10)    # This Means 10 random numbers between 10 and 20
a

array([10, 17, 15, 11, 17, 15, 14, 14, 15, 15], dtype=int32)

In [15]:
arr= np.arange(6)   # range from 0 to 6th index
print(arr)

[0 1 2 3 4 5]


In [16]:
arr2=np.random.randint(10,100,(10,10))   # Means randam numbers between 10 and 100, 10*10 matrix 
arr2

array([[98, 19, 24, 13, 14, 24, 62, 89, 83, 14],
       [89, 81, 83, 19, 60, 92, 49, 15, 63, 17],
       [61, 30, 99, 19, 91, 93, 42, 22, 97, 42],
       [39, 24, 95, 18, 29, 20, 74, 84, 73, 80],
       [55, 91, 80, 43, 32, 34, 84, 41, 93, 97],
       [40, 48, 56, 49, 90, 15, 48, 72, 66, 62],
       [16, 94, 57, 93, 98, 74, 29, 95, 88, 89],
       [57, 20, 32, 60, 25, 87, 32, 16, 48, 40],
       [52, 95, 49, 83, 76, 42, 24, 26, 83, 86],
       [35, 19, 87, 49, 18, 30, 62, 49, 79, 89]], dtype=int32)

In [17]:
arr[:4]      # one row upto 4th index

array([0, 1, 2, 3])

In [18]:
arr2[:]      # ':' means full matrix 

array([[98, 19, 24, 13, 14, 24, 62, 89, 83, 14],
       [89, 81, 83, 19, 60, 92, 49, 15, 63, 17],
       [61, 30, 99, 19, 91, 93, 42, 22, 97, 42],
       [39, 24, 95, 18, 29, 20, 74, 84, 73, 80],
       [55, 91, 80, 43, 32, 34, 84, 41, 93, 97],
       [40, 48, 56, 49, 90, 15, 48, 72, 66, 62],
       [16, 94, 57, 93, 98, 74, 29, 95, 88, 89],
       [57, 20, 32, 60, 25, 87, 32, 16, 48, 40],
       [52, 95, 49, 83, 76, 42, 24, 26, 83, 86],
       [35, 19, 87, 49, 18, 30, 62, 49, 79, 89]], dtype=int32)

In [19]:
arr2[0:5]    # first five rows

array([[98, 19, 24, 13, 14, 24, 62, 89, 83, 14],
       [89, 81, 83, 19, 60, 92, 49, 15, 63, 17],
       [61, 30, 99, 19, 91, 93, 42, 22, 97, 42],
       [39, 24, 95, 18, 29, 20, 74, 84, 73, 80],
       [55, 91, 80, 43, 32, 34, 84, 41, 93, 97]], dtype=int32)

In [20]:
print(arr2[1,4])      # second row 5 th element

60


In [21]:
print(arr2[-5,5])     # 5 th row from bottom and 6 the element 

15


In [22]:
print(arr2[-7,-9])    # 7 th row from bottom and 9 th element in reverse

24


In [23]:
print(arr2[::-3])    # Start from the last element row and take every 3rd element row going backward

[[35 19 87 49 18 30 62 49 79 89]
 [16 94 57 93 98 74 29 95 88 89]
 [39 24 95 18 29 20 74 84 73 80]
 [98 19 24 13 14 24 62 89 83 14]]


In [24]:
print(arr2[:-3])   # Take elements from the beginning up to (but not including) the last 3 elements

[[98 19 24 13 14 24 62 89 83 14]
 [89 81 83 19 60 92 49 15 63 17]
 [61 30 99 19 91 93 42 22 97 42]
 [39 24 95 18 29 20 74 84 73 80]
 [55 91 80 43 32 34 84 41 93 97]
 [40 48 56 49 90 15 48 72 66 62]
 [16 94 57 93 98 74 29 95 88 89]]


In [25]:
print(arr2[0:10:3])  # Start from index 0 and pick every 3rd element until index 10 (exclusive)

[[98 19 24 13 14 24 62 89 83 14]
 [39 24 95 18 29 20 74 84 73 80]
 [16 94 57 93 98 74 29 95 88 89]
 [35 19 87 49 18 30 62 49 79 89]]


In [26]:
print(arr2[3:])     # Take all elements starting from index 3 to the end

[[39 24 95 18 29 20 74 84 73 80]
 [55 91 80 43 32 34 84 41 93 97]
 [40 48 56 49 90 15 48 72 66 62]
 [16 94 57 93 98 74 29 95 88 89]
 [57 20 32 60 25 87 32 16 48 40]
 [52 95 49 83 76 42 24 26 83 86]
 [35 19 87 49 18 30 62 49 79 89]]


In [27]:
arr

array([0, 1, 2, 3, 4, 5])

In [28]:
print(arr.max())    # Gives you biggest number from array

5


In [29]:
print(arr.min())    # gives you the smallest number from array

0


In [30]:
print(arr.mean())   # It calculates the average (mean) of all elements in the array

2.5


In [31]:
print(np.median(arr))   # Median = the middle value of a dataset when it is arranged in order

2.5


In [32]:
from numpy import *    # 256 function called internally
a=array([1,2,3,4,5])
print(median(a))

3.0


# Numpy Indexing

In [33]:
mat=np.arange(0,100).reshape(10,10)  # Create numbers 0–99 and arrange them into a 10×10 matrix
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
row=7
col=2

print(row)
print(col)

7
2


In [35]:
print(mat[row,col])    # matrix with variables

72


In [36]:
col=6

In [37]:
print(mat[row,col])

76


In [38]:
# To Bring out Column Values
mat[:,col]     # we have already defined col = 6 so it is giving us 6th column output

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [39]:
mat[:,-5]   # 5 th column from reverse

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [40]:
mat[:,8]    # 9 th column from starting

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [41]:
mat[3]    # or mat [3,:] will bring out 3rd row 

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [42]:
mat[:3]   # Give me the first 3 rows (all columns included) and stop before 3 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [43]:
mat[3:7,3:7]   # It extracts a submatrix (block) from the original matrix.
               # 3:7 (rows) → rows 3, 4, 5, 6
               # 3:7 (columns) → columns 3, 4, 5, 6 
               # 7 is not included

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [44]:
mat[1:2,2:4]

array([[12, 13]])

# Numpy Masking

In [45]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
id(mat)

2144846080272

In [47]:
mat>50    # numbers >50 will be written as true and < 50 will be written as false

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [48]:
mat[mat>50]   # will give numbers instead of true or false

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
mat[mat!=50]   # will  give numbers which are not equal to 50 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:
print(mat[mat==50])   # will give numbers which are equal to 50

[50]


# 1) Array Creation Function

In [51]:
import numpy as np

In [52]:
# Create an array from list   
a=np.array([1,2,3])              # we convert list argument to array
print("Array a:", a)

Array a: [1 2 3]


In [53]:
# Create an array with evenly spaced values
b=np.arange(0,10,2)  # Values from 0 to 10 with step 2 
print("Array b:", b)

Array b: [0 2 4 6 8]


In [54]:
# Create an array with odd values
c=np.arange(0,10,3)
print("Array c:",c)

Array c: [0 3 6 9]


In [55]:
# create an array filled with zeros
d=np.zeros((2,3))  # 2*3 Array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [56]:
# create an array filled with zeros
d=np.zeros((2,3),dtype=int)  # 2*3 Array of zeros
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [57]:
# create an array filled with ones with 3*2 matrix
e=np.ones((3,2),dtype=int)
print("Array e:\n",e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [58]:
#Create a identity 4*4 matrix
f=np.eye(4)
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2) Array Manipulation function

In [59]:
# Reshape an Array Reshape into 1*3 ( 1 row three columns)
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [60]:
# Reshape an Array Reshape into 3*1( 3 row,1 columns)
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [61]:
#Flatten a 1D array
f1=np.array([[1,2],[3,4]])
flattened= np.ravel(f1)
print("Flattened Array;",flattened)

Flattened Array; [1 2 3 4]


In [62]:
# Transpose an array
e1=np.array([[1,2],[3,4]])
transposed= np.transpose(e1)
print("Transposed Array:\n", transposed)

Transposed Array:
 [[1 3]
 [2 4]]


In [63]:
# Stacks Array vertically
a2=np.array([1,2])
b2=np.array([3,4])
c2=np.array([5,6])
stacked=np.vstack([a2,b2,c2])
print("stacked arrays:\n",stacked)

stacked arrays:
 [[1 2]
 [3 4]
 [5 6]]
